FROM node:14-alpine

# Install development tools
RUN npm install typescript -g

# Set working directory
WORKDIR /app

# Copy project file
COPY package.json .

# Install ALL node_modules, including 'devDependencies'
RUN npm install

# Copy entire project
COPY . .

# Compile source in typescript
RUN tsc
